# Generated by Django 4.0 on 2022-02-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_organization_rename_owner_name_reservation_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last update time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last update time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last update time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last update time'),
        ),
    ]
